# Replace the text below to customize your site
site_name: Sami Piercy - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Sami Piercy
copyright: Copyleft 2022 "Sami Piercy" - GNU Free Documentation License
repo_name: 'Name : Github Repo'
site_url: https://fablabbcn.github.io/mdef-template/
repo_url: 'https://github.com/fablabbcn/mdef-template'


nav:
  - Home: index.md
  - About: about/me.md
  - Master project:
      - Initial ideas: project/project.md
      - Interventions: project/interventions.md
  - Reflections :
      - Term 1:
          - Bootcamp: term1/01-Bootcamp.md
          - Design Studio I: term1/02-Design Studio.md
          - AoWS: term1/03-Atlas of Weak Signals.md
          - Bio&Agro: term1/04-Bio&Agro.md
          - Living with Your Own Ideas: term1/05-LivingWithIdeas.md
          - Tech Beyond the Myth: term1/06-Tech Beyond the Myth.md
          - Community Engagement: term1/07-CommunityEngagement.md
          - Extended Intelligences: term1/08-Extended Intelligences.md

      - Term 2:
          - Design Studio II: term2/09-DesignStudioII.md
          - Design for the Next Billion Seconds: term2/10-BillionSeconds.md
          - Remixing Materials: term2/11-RemixingMaterials.md
          - Prototyping for Design: term2/12-PrototypingforDesign.md
          - Communicating Ideas: term2/13-CommunicatingIdeas.md
          - Making Sense and Meaning: term2/14-MakingSense.md
          - Measuring the World: term2/15-MeasuringTheWorld.md
          - Future Talks: term2/16-FutureTalks.md


      - Term 3: 
          - Design Studio III: term3/17-DesignStudioIII.md
          - Distributed Design: term3/18-DistributedDesign.md
          - Prototyping for Design II: term3/19-PrototypingforDesignII.md
          - Design Ethics: term3/20-DesignEthics.md
          - Critical Transfeminist Design: term3/21-CriticalTransfeministDesign.md
          - Collective Intelligence: term3/22-CollectiveIntelligences.md 
          - MDEFest: term3/23-MDEFest.md
              
      #    - digi: term1/01-Bootcamp.md
       #   - studio: term1/01-Bootcamp.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  palette: 
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    scheme: default
    primary: blue grey
    accent: amber
  font:
    # See available fonts at https://fonts.google.com/
    text: Montserrat
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
